### ISSUE TITLE
Check for affix talents

### ISSUE THREAD

**Issue by Thekinghim** [Thekinghim/keystone-companion#19]
in the dungeon when there is a ready check the addon could check if you picked a talent for the current affix or not. for example: long cc for incorporeal. if not, it would remind you with a /s message or something like that. the affix would only check your talents so the other players won't find it annoying because it would tell them what to do

@kaelonR @Larsj02

**Comment by Larsj02** [comment]
This should be easy, but it would need hard coded conditions like dungeon x = talent x or affix x = talent x for every class and spec

**Comment by Thekinghim** [comment]
What do you mean?

**Comment by Thekinghim** [comment]
Like finding that info would be no problem for me at all
