### ISSUE TITLE
Mythic score calculating

### ISSUE THREAD

**Issue by Thekinghim** [Thekinghim/keystone-companion#22]
Is there any way to add a simple calculator to it ? Lets say my rating is 2200... could it tell me what keys I need to run to get to 2500 ? For example it could take the 300 points I'm looking for and equally divide them and tell me each dungeon by how many levels I need to increase the key .

**Comment by Larsj02** [comment]
It's not that easy as the keys don't give the same point every time as it is changing based on how fast you're doing the key + how high the key is but we could do this calculation with base scores and maybe let the player decide the max key that he'd like to run and then calculate how many of these capped keys he'd need like

x score but i just wanna run 15s at max then the calculator would tell me do x 15s and a +12 for example to reach score x.

There would just be multiple solutions for reaching the score so we'd need some options for the user to either limit the results like with max key / min key or maybe even just display like top 5 results on how to reach that score or something
