### ISSUE TITLE
When i click calculate this error comes

### ISSUE THREAD

**Issue by Thekinghim** [Thekinghim/keystone-companion#45]
1x Keystone-Companion/scoreCalculator.lua:100: attempt to index a nil value
[string "@Keystone-Companion/scoreCalculator.lua"]:100: in function <Keystone-Companion/scoreCalculator.lua:99>
[string "@Keystone-Companion/scoreCalculator.lua"]:547: in function `ShowResults'
[string "@Keystone-Companion/scoreCalculator.lua"]:378: in function <Keystone-Companion/scoreCalculator.lua:368>

Locals:
(*temporary) = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = <function> defined =[C]:-1
(*temporary) = "attempt to index a nil value"
const = <table> {
 BASE_SCORE = <table> {
 }
 MAX_REMOVAL = 10
 AFFIX = <table> {
 }
 MAX_ADDITION = 5
 THRESHOLD = 0.400000
}

**Comment by Larsj02** [comment]
did you calculate with no values set or when did this happen?

**Comment by Thekinghim** [comment]
I had values on it i tired diffrent ones like 10 times then it worked
