### ISSUE TITLE
get this error on US servers only??

### ISSUE THREAD

**Issue by Thekinghim** [Thekinghim/keystone-companion#55]
Message: Interface/AddOns/Keystone-Companion/ui/main.lua:606: Usage: local className, classFilename, classID = UnitClass(unit)
Time: Sat Apr 27 14:41:57 2024
Count: 3
Stack: Interface/AddOns/Keystone-Companion/ui/main.lua:606: Usage: local className, classFilename, classID = UnitClass(unit)
[string "=[C]"]: ?
[string "=[C]"]: in function `UnitClass'
[string "@Interface/AddOns/Keystone-Companion/ui/main.lua"]:606: in function `RerenderPlayerRow'
[string "@Interface/AddOns/Keystone-Companion/ui/main.lua"]:685: in function `Rerender'
[string "@Interface/AddOns/Keystone-Companion/main.lua"]:98: in function <Interface/AddOns/Keystone-Companion/main.lua:49>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by Larsj02** [comment]
This was the same as the raid error so it's fixed now
