### ISSUE TITLE
Error on load - scoreCalculator.lua:262, Action[SetPoint] failed because [SetPoint would result in anchor family connection]

### ISSUE THREAD

**Issue by kaelonR** [Thekinghim/keystone-companion#62]
Happened with a clean install of the addon, without any prior WTF data.
![image](https://github.com/Thekinghim/keystone-companion/assets/28660369/f5f5cc54-f4b2-42c5-8c3e-7b0bdd01dd44)

**Comment by Larsj02** [comment]
was fixed https://github.com/Thekinghim/keystone-companion/commit/a2b210d08fbc32cc1952c186705dd613f42c365e
