### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by Larsj02** [Thekinghim/keystone-companion#63]
Refactoring the Code to have the Frame style match and cleaner / shorter / easier to read code.
Doing bug fixes on the side

**Comment by Thekinghim** [comment]
![6c65a158b2d9b4cf789df9ce27a20bc1](https://github.com/Thekinghim/keystone-companion/assets/151988881/2d910e60-2d0c-4709-b0e1-15b7e0110e0a)
Still problems with the text behind, Im on the refactoring branch
