### ISSUE TITLE
LUA errors when running addon in raid

### ISSUE THREAD

**Issue by rwygand** [Thekinghim/keystone-companion#65]
40x Keystone-Companion/ui/main.lua:612: Usage: local className, classFilename, classID = UnitClass(unit)
[string "=[C]"]: in function `UnitClass'
[string "@Keystone-Companion/ui/main.lua"]:612: in function `RerenderPlayerRow'
[string "@Keystone-Companion/ui/main.lua"]:691: in function `Rerender'
[string "@Keystone-Companion/main.lua"]:101: in function <Keystone-Companion/main.lua:49>

Locals:
(*temporary) = nil

**Comment by Larsj02** [comment]
This was fixed in [this Branch already](https://github.com/Thekinghim/keystone-companion/tree/63-refactoring) will do a new release soon. 
Thanks for the Report :)
