### ISSUE TITLE
Lua error while raid activity (after some mates leaving?), Lua Error line 612 repeatly

### ISSUE THREAD

**Issue by KaspOu** [Thekinghim/keystone-companion#68]
Lua Error line 612, happened outdoor while raid activity (Zaqali, Superbloom).
Happened at the end, when people were leaving raid (don't know if it was on each leave, or if it was periodically after on special event..)

23x Keystone-Companion/ui/main.lua:612: Usage: local className, classFilename, classID = UnitClass(unit)
[string "=[C]"]: in function `UnitClass'
[string "@Keystone-Companion/ui/main.lua"]:612: in function `RerenderPlayerRow'
[string "@Keystone-Companion/ui/main.lua"]:691: in function `Rerender'
[string "@Keystone-Companion/main.lua"]:101: in function <Keystone-Companion/main.lua:49>

Locals:
(*temporary) = nil

**Comment by Larsj02** [comment]
This one is already fixed in the next Release :)
